import { Hono } from "hono";
import { decrypt, encrypt, sha, token } from "./crypto";
import { parseNodes, renderMihomo, renderShadowrocket } from "./core";
import type { Env, ProxyNode, RuleManifest } from "./types";
const app=new Hono<{Bindings:Env}>();
const now=()=>Math.floor(Date.now()/1000);
async function authorized(c:any){const auth=c.req.header("authorization")||"";return auth.startsWith("Bearer ")&&(await sha(auth.slice(7)))===(await sha(c.env.ADMIN_TOKEN));}
async function manifest(env:Env){const r=await fetch(env.RULE_MANIFEST_URL,{headers:{"User-Agent":"fengsx-subscription-hub"},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`规则清单 HTTP ${r.status}`);const value=await r.json() as RuleManifest;if(value.schemaVersion!==1||!Array.isArray(value.rules))throw new Error("规则清单格式无效");return value;}
async function allNodes(env:Env):Promise<ProxyNode[]>{const rows=await env.DB.prepare("SELECT encrypted_payload FROM nodes n JOIN sources s ON s.id=n.source_id WHERE s.enabled=1 ORDER BY s.priority,n.sort_order").all<{encrypted_payload:string}>();const seen=new Set<string>(),out:ProxyNode[]=[];for(const row of rows.results){const p=JSON.parse(await decrypt(env.MASTER_KEY,row.encrypted_payload)) as ProxyNode;const k=JSON.stringify([p.type,p.server,p.port,p.uuid??p.password??""]);if(!seen.has(k)){seen.add(k);out.push(p);}}return out;}
async function build(env:Env){const id=crypto.randomUUID(),started=now();await env.DB.prepare("INSERT INTO builds(id,status,started_at) VALUES(?,'running',?)").bind(id,started).run();try{const [rules,nodes,tokens]=await Promise.all([manifest(env),allNodes(env),env.DB.prepare("SELECT token_hash FROM subscriptions WHERE enabled=1").all<{token_hash:string}>()]);if(!nodes.length)throw new Error("没有可用节点");const outputs={clash:renderMihomo(nodes,rules,false),merlinclash:renderMihomo(nodes,rules,true),shadowrocket:renderShadowrocket(nodes)};for(const item of tokens.results)for(const [format,content] of Object.entries(outputs))await env.ARTIFACTS.put(`sub:${item.token_hash}:${format}`,content,{metadata:{ruleSha:rules.source.sha256,nodeCount:nodes.length,builtAt:started}});await env.DB.prepare("UPDATE builds SET status='success',rule_sha=?,node_count=?,finished_at=? WHERE id=?").bind(rules.source.sha256,nodes.length,now(),id).run();return {nodes:nodes.length,ruleSha:rules.source.sha256};}catch(e){const msg=e instanceof Error?e.message:String(e);await env.DB.prepare("UPDATE builds SET status='failed',error=?,finished_at=? WHERE id=?").bind(msg.slice(0,300),now(),id).run();throw e;}}
async function refresh(env:Env){const sources=await env.DB.prepare("SELECT id,name,encrypted_url FROM sources WHERE enabled=1 ORDER BY priority").all<{id:string;name:string;encrypted_url:string}>();let total=0;for(const s of sources.results){try{const url=await decrypt(env.MASTER_KEY,s.encrypted_url);const r=await fetch(url,{headers:{"User-Agent":"Clash.Meta","Accept":"*/*"},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const nodes=await parseNodes(await r.text(),s.id);if(!nodes.length)throw new Error("未解析出支持的节点");const ts=now();const resolved=await Promise.all(nodes.map(n=>encrypt(env.MASTER_KEY,JSON.stringify(n.proxy))));const statements=[env.DB.prepare("DELETE FROM nodes WHERE source_id=?").bind(s.id),...nodes.map((n,i)=>env.DB.prepare("INSERT INTO nodes(id,source_id,fingerprint,name,region,protocol,encrypted_payload,sort_order,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(n.id,s.id,n.fingerprint,n.name,n.region,n.protocol,resolved[i],i,ts)),env.DB.prepare("UPDATE sources SET last_success_at=?,last_error=NULL,updated_at=? WHERE id=?").bind(ts,ts,s.id)];await env.DB.batch(statements);total+=nodes.length;}catch(e){await env.DB.prepare("UPDATE sources SET last_error=?,updated_at=? WHERE id=?").bind((e instanceof Error?e.message:String(e)).slice(0,300),now(),s.id).run();}}
return {...await build(env),rawNodes:total};}
const admin=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>fengsx 节点组装</title><style>body{font:15px system-ui;max-width:980px;margin:32px auto;padding:0 16px;background:#f6f7fb;color:#18202a}section{background:white;padding:20px;margin:16px 0;border-radius:14px;box-shadow:0 4px 20px #0001}input,button{padding:10px;margin:5px;border:1px solid #ccd;border-radius:8px}input[type=url]{width:min(680px,90%)}button{background:#1769e0;color:white}pre{white-space:pre-wrap;word-break:break-all}</style><h1>fengsx 节点组装</h1><section><input id="key" type="password" placeholder="管理员令牌"><button onclick="load()">登录/刷新</button></section><section><h2>新增订阅来源</h2><input id="name" placeholder="名称"><input id="url" type="url" placeholder="HTTPS 订阅地址"><button onclick="add()">添加并分析</button></section><section><button onclick="refresh()">刷新全部并重新组装</button><button onclick="createSub()">创建客户端订阅</button><pre id="out"></pre></section><script>let key=localStorage.key||'';document.querySelector('#key').value=key;async function api(path,opt={}){key=document.querySelector('#key').value;localStorage.key=key;const r=await fetch(path,{...opt,headers:{'Authorization':'Bearer '+key,'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):{};}async function load(){try{out.textContent=JSON.stringify(await api('/api/state'),null,2)}catch(e){out.textContent=e}}async function add(){try{await api('/api/sources',{method:'POST',body:JSON.stringify({name:name.value,url:url.value})});await refresh()}catch(e){out.textContent=e}}async function refresh(){try{out.textContent=JSON.stringify(await api('/api/refresh',{method:'POST'}),null,2);await load()}catch(e){out.textContent=e}}async function createSub(){try{out.textContent=JSON.stringify(await api('/api/subscriptions',{method:'POST',body:JSON.stringify({label:'默认订阅'})}),null,2)}catch(e){out.textContent=e}}</script></html>`;
app.get("/",c=>c.redirect("/admin"));app.get("/admin",c=>c.html(admin));app.get("/health",c=>c.json({ok:true,rules:c.env.RULE_MANIFEST_URL}));
app.use("/api/*",async(c,next)=>{if(!await authorized(c))return c.json({error:"未授权"},401);await next();});
app.get("/api/state",async c=>{const [sources,nodes,builds,subs]=await Promise.all([c.env.DB.prepare("SELECT id,name,enabled,priority,last_success_at,last_error FROM sources ORDER BY priority").all(),c.env.DB.prepare("SELECT source_id,protocol,region,COUNT(*) count FROM nodes GROUP BY source_id,protocol,region").all(),c.env.DB.prepare("SELECT status,rule_sha,node_count,error,started_at,finished_at FROM builds ORDER BY started_at DESC LIMIT 10").all(),c.env.DB.prepare("SELECT label,enabled,created_at,last_access_at FROM subscriptions ORDER BY created_at DESC").all()]);return c.json({sources:sources.results,nodeSummary:nodes.results,builds:builds.results,subscriptions:subs.results});});
app.post("/api/sources",async c=>{const body=await c.req.json<{name:string;url:string}>();const u=new URL(body.url);if(u.protocol!=="https:")return c.json({error:"只允许 HTTPS"},400);const id=crypto.randomUUID(),ts=now();await c.env.DB.prepare("INSERT INTO sources(id,name,encrypted_url,created_at,updated_at) VALUES(?,?,?,?,?)").bind(id,body.name.trim(),await encrypt(c.env.MASTER_KEY,u.toString()),ts,ts).run();return c.json({id},201);});
app.post("/api/refresh",async c=>c.json(await refresh(c.env)));
app.post("/api/subscriptions",async c=>{const body=await c.req.json<{label?:string}>();const value=token(),hash=await sha(value),ts=now();await c.env.DB.prepare("INSERT INTO subscriptions(token_hash,encrypted_token,label,created_at) VALUES(?,?,?,?)").bind(hash,await encrypt(c.env.MASTER_KEY,value),body.label||"订阅",ts).run();await build(c.env);const base=new URL(c.req.url).origin;return c.json({token:value,clash:`${base}/s/${value}/clash`,merlinclash:`${base}/s/${value}/merlinclash`,shadowrocket:`${base}/s/${value}/shadowrocket`},201);});
app.get("/s/:token/:format",async c=>{const format=c.req.param("format");if(!["clash","merlinclash","shadowrocket"].includes(format))return c.notFound();const hash=await sha(c.req.param("token"));const valid=await c.env.DB.prepare("SELECT 1 ok FROM subscriptions WHERE token_hash=? AND enabled=1").bind(hash).first();if(!valid)return c.notFound();let value=await c.env.ARTIFACTS.getWithMetadata(`sub:${hash}:${format}`);if(!value.value){await build(c.env);value=await c.env.ARTIFACTS.getWithMetadata(`sub:${hash}:${format}`);}if(!value.value)return c.notFound();c.executionCtx.waitUntil(c.env.DB.prepare("UPDATE subscriptions SET last_access_at=? WHERE token_hash=?").bind(now(),hash).run());c.header("Cache-Control","no-store");c.header("Content-Type",format==="shadowrocket"?"text/plain; charset=utf-8":"application/yaml; charset=utf-8");return c.body(value.value);});
export default {fetch:app.fetch,scheduled(_c:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(refresh(env));}};
